### ISSUE TITLE
2023.3.2 support

### ISSUE THREAD

**Issue by rwnd-bradley** [kdl-org/intellij-kdl#8]
Currently not compatible with the latest version (IntelliJ IDEA 2023.3.2).

**Comment by bobuk** [comment]
is it possible to update this build to support current versions of JetBrains products?
btw looks like now it's not necessary to mark the upper version of the supported platform, only the bottom one.

**Comment by rwnd-bradley** [comment]
Bumping for support in 2024.1:
`Plugin 'KDL Document Language' (version '2.0.0') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-241.14494.240`

**Comment by rwnd-bradley** [comment]
Closing since this is now supported, thank you!
